// examples/service/react/src/app.tsx
import { useState } from "react";
import clsx from "clsx";
import "./styles.css";
import useOnline from "./use-online";
import useWhenOnline from "./use-when-online";

export default function App() {
  // Simple counter state for the sake of the example.
  const [counter, setCounter] = useState(1);

  // Log the counter to the console when the user is online. Buffer the logs
  // if the user is offline.
  const log = useWhenOnline((counter) => console.log(counter));

  // Get the online status.
  const isOnline = useOnline();

  return (
    <div className="App">
      <div
        className={
          // Use clsx to conditionally add the "is-online" class.
          clsx("OnlineBanner", isOnline && "is-online")
        }
      >
        {isOnline ? "Online" : "Offline"}
      </div>

      <button
        onClick={() => {
          // Log the counter to the console.
          log(counter);

          // Increment the counter.
          setCounter(counter + 1);
        }}
      >
        Counter: {counter}
      </button>
    </div>
  );
}

// examples/service/angular-service/src/app/app.component.ts
import { Component, inject } from "@angular/core";
import { OnlineService } from "./online.service";
import { WhenOnline } from "./when-online";

@Component({
  selector: "app-root",
  templateUrl: "./app.component.html",
  styleUrls: ["./app.component.css"],
})
export class AppComponent {
  // Use the inject function to get the isOnline observable. Can be used to
  // mock the observable in tests.
  onlineService = inject(OnlineService);

  // Create a new WhenOnline instance. Logs the counter to the console when
  // the user is online. Stashes the logs when the user is offline.
  whenOnline = new WhenOnline(this.onlineService, (counter: number) => {
    console.log(`Counter: ${counter}`);
  });

  // Counter state for the sake of the example.
  counter = 1;

  ngOnInit() {
    // Initialize listeners.
    this.whenOnline.init();
  }

  ngOnDestroy() {
    // Destroy listeners.
    this.whenOnline.destroy();
  }

  handleButtonClick() {
    // Call the callback when the user is online, or stash the call when the
    // user is offline.
    this.whenOnline.next(this.counter);

    // Increment the counter.
    this.counter += 1;
  }
}

<div class="online-banner" [class.is-online]="onlineService.online$ | async">
  {{ (onlineService.online$ | async) ? "🟢 Online" : "🔴 Offline" }}
</div>

<div>
  <button (click)="handleButtonClick()">Counter: {{ counter }}</button>{{ " " }}
  <button (click)="onlineService.toggle()">
    {{ (onlineService.online$ | async) ? "Go online" : "Go offline" }}
  </button>
</div>
