// examples/service/react-component/src/app.tsx
import clsx from "clsx";
import { useEffect, useRef, useState } from "react";
import "./styles.css";
import toggleOnline from "./toggle-online";

export default function App() {
  // State to track whether the user is online or offline.
  const [isOnline, setIsOnline] = useState(() => navigator.onLine);

  // Add an event listener to update the online status.
  useEffect(() => {
    const handleOnline = () => {
      console.log("-- Went online --");

      setIsOnline(true);
    };
    const handleOffline = () => {
      console.log("-- Went offline --");

      setIsOnline(false);
    };

    // Add event listeners.
    window.addEventListener("online", handleOnline);
    window.addEventListener("offline", handleOffline);

    // Remove event listeners on cleanup.
    return () => {
      window.removeEventListener("online", handleOnline);
      window.removeEventListener("offline", handleOffline);
    };
  }, []);

  // Simple counter state for the sake of the example.
  const [counter, setCounter] = useState(1);

  // Log the counter to the console.
  const logCounter = (counter: number) => {
    console.log(`Counter: ${counter}`);
  };

  // Keep track of the counters that were logged while the user was offline.
  const stashedCountersRef = useRef<number[]>([]);

  // When the user comes back online, log the counters that were stashed.
  // See the dependency array below to see how this effect knows about the
  // `isOnline` state.
  useEffect(() => {
    if (isOnline && stashedCountersRef.current.length > 0) {
      stashedCountersRef.current.map((counter) => logCounter(counter));
      stashedCountersRef.current.length = 0;
    }
  }, [isOnline]);

  // Handle clicks on the counter button. Log the counter to the console if
  // the user is online. Otherwise, buffer the counter.
  const handleClick = () => {
    if (isOnline) {
      logCounter(counter);
    } else {
      stashedCountersRef.current.push(counter);
    }

    // Increment the counter.
    setCounter(counter + 1);
  };

  return (
    <div className="App">
      <div
        className={
          // Use clsx to conditionally add the "is-online" class.
          clsx("OnlineBanner", isOnline && "is-online")
        }
      >
        {isOnline ? "🟢 Online" : "🔴 Offline"}
      </div>
      <div>
        <button onClick={handleClick}>Counter: {counter}</button>{" "}
        <button onClick={() => toggleOnline()}>
          {isOnline ? "Go offline" : "Go online"}
        </button>
      </div>
    </div>
  );
}

// examples/service/angular-component/src/app/app.component.ts
import { Component } from "@angular/core";

@Component({
  selector: "app-root",
  templateUrl: "./app.component.html",
  styleUrls: ["./app.component.css"],
})
export class AppComponent {
  // Flag to indicate whether the user is online or not.
  online = navigator.onLine;

  // Counter state for the sake of the example.
  counter = 1;

  // Stash counters when the user is offline.
  private stashedCounters: number[] = [];

  ngOnInit() {
    // Initialize listeners for online and offline events.
    window.addEventListener("online", this.handleOnline);
    window.addEventListener("offline", this.handleOffline);
  }

  ngOnDestroy() {
    // Remove listeners for online and offline events.
    window.removeEventListener("online", this.handleOnline);
    window.removeEventListener("offline", this.handleOffline);
  }

  handleButtonClick() {
    // Call the callback when the user is online, or stash the call when the
    // user is offline.
    if (this.online) {
      this.logCounter(this.counter);
    } else {
      this.stashedCounters.push(this.counter);
    }

    // Increment the counter.
    this.counter += 1;
  }

  toggleOnline(isOnline = !this.online) {
    window.dispatchEvent(new Event(isOnline ? "online" : "offline"));
  }

  private handleOnline = () => {
    console.log("-- Went online --");

    this.online = true;

    // Log stashed counters when the user is online.
    if (this.stashedCounters.length > 0) {
      this.stashedCounters.map((counter) => this.logCounter(counter));
      this.stashedCounters.length = 0;
    }
  };

  private handleOffline = () => {
    console.log("-- Went offline --");

    this.online = false;
  };

  private logCounter(counter: number) {
    console.log(`Counter: ${counter}`);
  }
}

<div class="online-banner" [class.is-online]="online">
  {{ online ? "🟢 Online" : "🔴 Offline" }}
</div>

<div>
  <button (click)="handleButtonClick()">Counter: {{ counter }}</button>{{ " " }}
  <button (click)="toggleOnline()">
    {{ online ? "Go offline" : "Go online" }}
  </button>
</div>
