// examples/component/react-1/src/app.tsx
import { useMemo } from "react";
import { Heading, Stack } from "@chakra-ui/react";
import BetterButton from "./better-button.tsx";

export default function App() {
  const isDisabled = useMemo(() => Math.random() > 0.5, []);

  const onClick = () => {
    if (isDisabled) {
      alert("You are not lucky enough to click me.");
      return;
    }

    console.log("You clicked me!");
  };

  return (
    <>
      <Stack alignItems="center">
        <Heading>Label</Heading>
        <BetterButton
          onClick={onClick}
          colorScheme={isDisabled ? "pink" : undefined}
        >
          Click me!
        </BetterButton>
        <div>
          If you are lucky you can click me 2 times and something will happen.
          If you are not you are informed about it.
        </div>
      </Stack>
    </>
  );
}

// examples/component/angular-3/src/app/app.component.ts
import { Component } from "@angular/core";

@Component({
  selector: "app-root",
  templateUrl: "./app.component.html",
  styleUrls: ["./app.component.css"],
})
export class AppComponent {
  protected isDisabled = Math.random() > 0.5;

  protected click(event: Event) {
    if (event.defaultPrevented) {
      return;
    }
    console.log("You clicked me!");
  }
}

<app-container>
  <ng-container label>Label</ng-container>
  <ng-container>
    <app-disable-reason-button
      (click)="click($event)"
      [isDisabled]="isDisabled"
      color="primary"
      reason="You are not lucky enough to click me."
      >Click me
    </app-disable-reason-button>
  </ng-container>
  <ng-container info>
    If you are lucky you can click me 2 times and something will happen. If you
    are not you are informed about it.
  </ng-container>
</app-container>
