// examples/component/angular-1/src/app/app.component.ts
import { Component } from "@angular/core";

@Component({
  selector: "app-root",
  templateUrl: "./app.component.html",
  styleUrls: ["./app.component.css"],
})
export class AppComponent {
  protected isDisabled = Math.random() > 0.5;

  protected showReason() {
    alert("Bad Luck!");
  }

  protected click(event: Event) {
    if (event.defaultPrevented) {
      return;
    }
    console.log("You clicked me!");
  }
}

<div class="container">
  <div class="label">Label</div>
  <button
    *ngIf="isDisabled"
    color="primary"
    mat-raised-button
    (click)="showReason()"
  >
    No Luck
  </button>
  <button
    *ngIf="!isDisabled"
    color="primary"
    (click)="click($event)"
    mat-raised-button
  >
    Got Lucky
  </button>
  <div class="info">
    If you are lucky you can click me 2 times and something will happen. If you
    are not you are informed about it.
  </div>
</div>

// examples/component/react-2/src/app.tsx
import { useMemo } from "react";
import BetterButton from "./better-button.tsx";
import Container from "./container.tsx";

export default function App() {
  const isDisabled = useMemo(() => Math.random() > 0.5, []);

  const onClick = () => {
    if (isDisabled) {
      alert("You are not lucky enough to click me.");
      return;
    }

    console.log("You clicked me!");
  };

  return (
    <>
      <Container
        heading="Label"
        info="If you are lucky you can click me 2 times and something will happen. If you are not you are informed about it."
      >
        <BetterButton
          onClick={onClick}
          colorScheme={isDisabled ? "pink" : undefined}
        >
          Click me!
        </BetterButton>
      </Container>
    </>
  );
}
